### ISSUE TITLE
The example it's not working

### ISSUE THREAD

**Issue by vini8cs** [jonas-fuchs/BAMdash#11]
I tried the command, but I'm getting this error:

`bamdash -b HEV.bam -r HEV-pat-1 -t HEV.vcf HEVprim.bed HEVamp.bed HEV.gb`
`[W::vcf_parse] Contig 'HEV-pat-1' is not defined in the header. (Quick workaround: index the file with tabix.)`

Another question is related to the running time. I was plotting a specific virus coverage using only the bed info in the -t command. Is it normal to take more than one day to run? I tried the "--export_static" with pdf. Could this be slowing the process?

**Comment by jonas-fuchs** [comment]
Hi vini8cs, so the warning you encountered is normal with this example as the #CHROM identifier is not defined in the header (our NGS workflow does not do this for some reason). However, pysam should read the vcf just fine and the plot should be produced. The only constraint is then that one needs to know the CHROM identifier beforehand. Could you check if the plot is still produced on your side?

**Comment by jonas-fuchs** [comment]
Regarding running time. No bamdash should not run a day! The only running time constraint is normally the size of the bam, but for all examples I have tried, the running time was fast (seconds to maybe a few mins if the bam was really large - >1 GB). Can you give me an indication how large your bam file was and try running it just with the bam file and no other arguments? There might be a bug to be fixed on my side. Export static could produce an issue, but without further info its hard to tell!

**Comment by vini8cs** [comment]
Hi, jonas! The HEV-pat-1_plot.pdf was created, despite the warning. The problem is with my data, which is taking more than one day to run and it's still running. The size of my bam is 4.3GB. The command is working only when I use the bam file. However, when I add the .bed file, the command never stops running. This is the head of my bed file; it's 543M long:

`Contig1	0	70	SRR1255326.230370/2	0	+
Contig1	0	58	SRR1255326.13208570/2	0	+
Contig1	0	64	SRR1255326.13698750/2	0	+
Contig1	0	68	SRR1255326.23776683/2	0	+
Contig1	0	59	SRR1255326.2338904/1	0	-
Contig1	0	60	SRR1255326.4227482/2	2	-
Contig1	0	103	SRR1255326.7908072/1	3	-
Contig1	0	61	SRR1255326.16090981/2	0	-
Contig1	0	70	SRR1255326.17535563/2	0	-
Contig1	0	61	SRR1255326.21782943/2	0	-
`

The command is: 

`bamdash -b deformed_wing_virus_sorted.bam -r Contig1 -t deformed_wing_virus.bed -e pdf`

It ran when I didn't specify the -e pdf, creating only an HTML file, but it's not opening.

Another question regarding the example with HEV is: is the command not supposed to generate the coverage for both strands? Such as in this image?

![WhatsApp Image 2023-11-21 at 14 35 15](https://github.com/jonas-fuchs/BAMdash/assets/96088485/4799d14a-f114-4665-bd22-74edc20fd792)

**Comment by jonas-fuchs** [comment]
Hi vini8cs, 

ah ok good to hear that the example is running on your end. The large bed file probably explains quite a lot. The plot is intended to show bed files as annotations below the plot (for example something like gene annatations, primers etc which should not have more than a few kb). Its loaded as a pd dataframe and then the script tries to figure out where to plot everything which is likely not super efficient. I guess your bed file is the location of individual reads? This will likely not be displayed properly anyways and better to use a genebrowser for such occasions. Also explains why the html won't open. Its simply too large. All the bed data is stored within the single html file due to how plotly handels the hover information.

BamDASH is sadly not that powerful. I will include something that performs some sort of check if the data will be able to plot and update the README. 

Reagrding the strands: No, at the moment the coverage is calculate cummulative for both strands. I will check if something like the upper plot would be possible with the samtools python implementation pysam and get back to you!

Hoped that helped.

**Comment by vini8cs** [comment]
I see. Make sense, the data is too big. I think plotting each strand separately would be more interesting than in a cumulative way for both strands, especially because most of the coverage for viruses is plotted this way.

**Comment by vini8cs** [comment]
Great! Thank you very much!
